openapi: 3.0.0
info:
  description: "Passwordless service wrapper"
  version: "1.0.0"
  title: "Swagger Passwordless"
  contact:
    email: "maxim.thomas@gmail.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
servers:
  - url: /otp/v1
tags:
  - name: "otp"
    description: "OTP via SMS or Email"
paths:
  /{settingId}/send:
    post:
      tags:
        - "otp"
      summary: "Sends SMS or email with OTP to client"
      description: ""
      operationId: "sendOTP"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SendOTP"
      parameters:
        - in: "path"
          name: "settingId"
          schema:
            type: "string"
          required: true
      responses:
        200:
          description: "successful operation"
          content:
            "appliaction/json":
              schema:
                $ref: "#/components/schemas/SendOTPResult"
      security:
        - bearerAuth: []

  /verify:
    post:
      tags:
        - "otp"
      summary: "Verifies OTP"
      description: "Multiple status values can be provided with comma separated strings"
      operationId: "verifyOTP"

      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/VerifyOTP"
      responses:
        200:
          description: "successful operation"
          content:
            "appliaction/json":
              schema:
                $ref: "#/components/schemas/VerifyOTPResult"
      security:
        - bearerAuth: []

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
  schemas:
    SendOTPRequest:
      type: "object"
      properties:
        destination:
          type: "string"
    SendOTPResult:
      type: "object"
      properties:
        operationId:
          type: "string"
    VerifyOTPRequest:
      type: "object"
      properties:
        operationId:
          type: "string"
        otp:
          type: "string"
          description: "OTP value"
    VerifyOTPResult:
      type: "object"
      properties:
        verified:
          type: "boolean"
