spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: username@gmail.com
    password: userpassword
    protocol: smtp
    tls: true
    properties.mail.smtp:
      auth: true
      starttls.enable: true
      ssl.trust: smtp.gmail.com